config/routes.rb
SimpleKpi::Application.routes.draw do

    resources :kpis
    resources :businesskpis  

   
    resources :bkdetails do 
      collection do 
        get 'dataEntry'
        get 'dataFeed'
      end
    end 

    get 'businesses/home'
    resources :franchisemasters   

    resources :businesses do
      collection do
        post 'savelinkkpi'
        get 'businesslinkkpi'        
      end
    end

  match '/get_target_percentage' => 'bkdetails#get_target_percentage'

  namespace :api do 
    namespace :v1 do
     post 'kpis/create' => 'kpis#create'
     post 'bkdetails/create' => 'bkdetails#create'
    end

  end

                         

  root :to => 'businesses#home'

end

app/models/business.rb
class Business < ActiveRecord::Base
  attr_accessible :branchaddress, :branchname, :branchtype, :city, :contactnumbers, :emailid, :facebook_id, :maplink, :owner_id, :shortname, :twitter_id, :workinghours
  
  has_many :bkdetails
  has_many :businesskpi
  has_many :kpi, through: :businesskpi 
   
  
  validates :branchaddress,:branchname,:contactnumbers,:branchtype,:city,:workinghours,:shortname,:maplink,:presence => true
  validates :branchname,:shortname, :length => { :maximum =>10 }
  validates :branchname,:uniqueness => true
 #  validates :contactnumbers,format: { with: /\d{3}-\d{3}-\d{4}/, message: "Valid Format :xxx-xxx-xxx" }


end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

	def index
	  @businesses = Business.all
    	respond_to do |format|
      	format.html # index.html.erb
      	format.xml  { render json: @businesses }
  	  end
  end

  def new
	  @business = Business.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @business }
      end
  end

  def show
    @business = Business.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @business }
      end
  end

  def create
    @business = Business.new(params[:business])
      respond_to do |format|
        if @business.save
          format.html { redirect_to @business, notice: 'Branch successfully added.' }
          format.json { render json: @business, status: :created, location: @business }
        else
          format.html { render action: "new" }
          format.json { render json: @business.errors, status: :unprocessable_entity }
        end
      end
  end

  def update
    @business = Business.find(params[:id])
      respond_to do |format|
        if @business.update_attributes(params[:business])
          format.html { redirect_to @business, notice: 'Branch Details successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @business.errors, status: :unprocessable_entity }
        end
      end
  end

  def edit
    @business = Business.find(params[:id])
  end


  def destroy
    @business = Business.find(params[:id])
    @business.destroy
      respond_to do |format|
        format.html { redirect_to @business }
        format.json { head :no_content }
      end
  end

  def businesslinkkpi
  @businesskpi = BusinessKpi.new
  @business = Business.find(params[:business_id])
  @mapped_kpi_ids = BusinessKpi.where(:business_id => @business.id).pluck('kpi_id')
  @kpi = Kpi.all
    respond_to do |format|
    format.html # index.html.erb
    format.xml  { render json: @businesskpi }
    end
  end  

  def savelinkkpi  
    @business = Business.find(params[:business_id])    
    BusinessKpi.where(:business_id => @business.id).destroy_all
    add_kpi_ids= params[:kpi_ids]
    add_kpi_ids.each do |kpi_id|
      bk=BusinessKpi.new
      bk.kpi_id = kpi_id.to_i
      bk.business_id = params[:business_id].to_i
      bk.save
    end   
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render json: @businesskpi }
    end
  end

end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for @business do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@business.errors.count, "error") %> occured while processing:</h3>
        <ul>
          <% @business.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>    
  <br />
   
  <h4>Branch Details</h4>
    <div>
      <%= f.label 'Branch Name*' %>
      <%= f.text_field :branchname, :class => 'title simple custom', :maxlength => 50, :style => 'width:633px'%>
    </div>
    
    <div>
      <%= f.label 'Branch Type*' %>
      <%= f.select :branchtype,%w{Parentbranch Subsidary},:include_blank => true %> 
    </div>
   
    <div>
      <%= f.label 'Short Name*'%>
      <%= f.text_field :shortname, :class => 'title simple', :maxlength => 50, :style => 'width:633px'%>
    </div>
    
    <div>
      <%= f.label 'City*'%>  
      <%= f.select :city,["Bangalore","Chennai","Delhi","Hyderabad","Mumbai","Kolkatta"],:include_blank => true %>
    </div>
    
    <div>
      <%= f.label 'Address*'%>
      <%= f.text_field :branchaddress, :class => 'title simple', :maxlength => 500, :style => 'width:633px'%>
    </div>
    

    <div>
      <%= f.label 'Contact Numbers*'%>
      <%= f.text_field :contactnumbers, :class => 'title simple', :maxlength => 50, :style => 'width:633px'%>
    </div>
    
    <div>
      <%= f.label  'Working Hours'%>
      <%= f.text_field :workinghours, :class => 'title simple', :maxlength => 100, :style => 'width:633px' , :value => 'Hours 10:00 AM TO 9:00 PM, MONDAY HOLIDAY'%>
    </div>
    
    <div>
      <%= f.label :Map_link,'Map Link' %>
      <%= f.text_field :maplink, :class => 'title simple', :maxlength => 200, :style => 'width:633px'%>
    </div>

    <div>
      <%= f.label 'Owner ID' %>
      <%= f.text_field :owner_id, :class => 'title simple', :maxlength => 200, :style => 'width:633px'%>
    </div>
              
    <div class="actions">
      <%=f.submit "Submit" ,:class=>["btn","btn-primary"] %>
    </div>

    <% end %>
    

app/views/businesses/businesslinkkpi.html.erb
<%= form_tag ("/businesses/savelinkkpi ") do %>
<%= hidden_field_tag :business_id, @business.id %> 
<%= label_tag("Business Name:")%>
<%= @business.branchname %>
	<table class="table">
		<thead>    
      		<th>Select </th>
      		<th>KPI Name</th>              
      		<th>Frequency</th>
      		<th>Category</th>
    	</thead>        
        <% if !@kpi.blank? %>
		    <% @kpi.each do |kpi| %>	  	
	  		 	<tr>	
	  	  			<td><%= check_box_tag "kpi_ids[]",kpi.id,@mapped_kpi_ids.include?(kpi.id)%></td>
	  	  			<td><%= kpi.KPIName %></td>        			
	  	  			<td><%= kpi.KPIEntryPeriod %></td>  
	      			<td><%= kpi.KPICategory %></td> 	      			
    			</tr>	    
	    	<% end %>    
		<% end %>
	</table> 

<div class="actions">
    <%= submit_tag %>,
</div>

<% end %>

app/views/businesses/edit.html.erb
<h4>Editing Branch Details</h4>
<%= render 'form' %>
    
<%= link_to "Back", businesses_path,:class=>["btn","btn-default"] ,:id=>"backbutton"%>
<%= link_to 'Show', @business,:class=>["btn","btn-default"] ,:id=>"backbutton" %> 
    

app/views/businesses/home.html.erb
<h4>Select the required action</h4>

<div class="center hero-unit">
  <%= link_to "Branch Registration",businesses_path, class: "btn btn-sm btn-primary"%>
  <%= link_to "Owner Registration",franchisemasters_path, class: "btn btn-sm btn-primary"%>
 
  <%= link_to "New KPI",new_kpi_path,class:"btn btn-sm btn-primary"%> 
</div>


  

app/views/businesses/index.html.erb
<div>
  <h4>
    <%= link_to  new_business_path, :class => [:btn, :"btn-success"] do |l|%>
      <i class="icon-plus-sign icon-white"></i>
      Add New Branch
    <% end %>
  </h4>

  <table class="table table-striped table-bordered">
    <thead>
      <th>Branch Name</th>          
      <th>City</th>
      <th>Contact Numbers</th>      
    </thead>

    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.branchname %></td>               
        <td><%= business.city %></td>
        <td><%= business.contactnumbers%></td>               
        <td><%= link_to 'Show', business %> 
            <%= link_to 'Edit', edit_business_path(business) %>
            <%= link_to 'Destroy',business, method: :delete, data: {confirm: 'Are you sure?'} %> 
            <%= link_to 'AddKPIData',dataEntry_bkdetails_path(:business_id => business.id),:class=>["btn","btn-default"] %>
            <%=link_to 'Feed',dataFeed_bkdetails_path(:business_id => business.id),:class => [:btn, :"btn-success"]%>
            <%=link_to 'LinkKpi',businesslinkkpi_businesses_path(:business_id => business.id),:class => [:btn, :"btn-success"]%>   

        </td>    
      </tr>
    <% end %>
  </table>
  <br />
</div>

app/views/businesses/new.html.erb
<%= render "form" %>

app/views/businesses/savelinkkpi.html.erb
 KPI Linked to the Business 
 <%= link_to 'Back', businesses_path ,:class=>["btn","btn-default"] ,:id=>"backbutton"%>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Branch Name:</b>
  <%= @business.branchname %>
</p>

<p>
  <b>Branch Type:</b>
  <%= @business.branchtype %>
</p>

<p>
  <b>Short Name:</b>
  <%= @business.shortname %>
</p>

<p>
  <b>City:</b>
  <%= @business.city %>
</p>


<p>
  <b>Branch Address:</b>
  <%= @business.branchaddress %>
</p>

<p>
  <b>Contact Numbers</b>
  <%= @business.contactnumbers %>
</p>

<p>
  <b>Working Hours</b>
  <%= @business.workinghours %>
</p>

<p>
  <b>Map Link:</b>
  <%= @business.maplink %>
</p>

<%= link_to 'Edit', edit_business_path %> |
<%= link_to 'Back', businesses_path %>