config/routes.rb
SimpleKpi::Application.routes.draw do

    resources :kpis
    resources :businesskpis  

   
    resources :bkdetails do 
      collection do 
        get 'dataEntry'
        get 'dataFeed'
      end
    end 

    get 'businesses/home'
    resources :franchisemasters   

    resources :businesses do
      collection do
        post 'savelinkkpi'
        get 'businesslinkkpi'        
      end
    end

  match '/get_target_percentage' => 'bkdetails#get_target_percentage'

  namespace :api do 
    namespace :v1 do
     post 'kpis/create' => 'kpis#create'
     post 'bkdetails/create' => 'bkdetails#create'
    end

  end

                         

  root :to => 'businesses#home'

end

app/models/bkdetail.rb
class Bkdetail < ActiveRecord::Base
  attr_accessible :actualValue, :business_id, :businesskpi_id, :kpi_id, :logDate, :notes, :targetPercentage, :targetValue

  belongs_to :kpi
  belongs_to :business
  belongs_to :businesskpi

  validates  :actualValue,:logDate,:presence => true
  validates  :logDate,:uniqueness => true 
  
end

app/controllers/api/v1/bkdetails_controller.rb
class Api::V1::BkdetailsController < ApplicationController
   respond_to :xml, :json
    
  def create   
   @bkdetail= Bkdetail.new(params[:details])
   @kpi=Kpi.find(params[:details][:kpi_id])
   #@businesskpi=BusinessKpi.where("kpi_id = ? and business_id = ? ",@bkdetail.kpi_id,@bkdetail.business_id)       
   @bkpi=BusinessKpi.where(kpi_id: @bkdetail.kpi_id, business_id: @bkdetail.business_id).first
   @bkdetail.businesskpi_id = @bkpi.id
   @bkdetail.targetValue=@kpi.KPITargetValue   
   @bkdetail.targetPercentage=( (@bkdetail.actualValue).to_f / (@bkdetail.targetValue).to_f * 100)-100
   
     if @bkdetail.save        
        render :json => @bkdetail.to_json
      else        
        render :json => {:errors => @bkdetail.errors.full_messages }
      end
    end 
end 
  


  
   

app/controllers/bkdetails_controller.rb
class BkdetailsController < ApplicationController

	def index
     @bks = Bkdetail.all
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render json: @bks }
      end
  end   

  def new
    @business = Business.find(params[:business_id])   
    @kpi = Kpi.find(params[:kpi_id])
    @bkpi = BusinessKpi.find(params[:businesskpi_id])
    @bks = Bkdetail.where("kpi_id = ? and business_id = ? and businesskpi_id =? ",@kpi.id,@business.id,@bkpi.id)    
    @bkdetail = Bkdetail.new
    
    respond_to do |format|
        format.html # new.html.erb
        format.json { render :text => @bkdetail.to_json }
    end
  end
    
  def show
    @bkdetail = Bkdetail.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @bkdetail}
      end
  end

  def create   
    @bkdetail = Bkdetail.new(params[:bkdetail])     
    @bks = Bkdetail.where("kpi_id = ? and business_id = ? and businesskpi_id =? ",@bkdetail.kpi_id,@bkdetail.business_id,@bkdetail.businesskpi_id)        
    @business = Business.find(@bkdetail.business_id)       
    @bkpi = BusinessKpi.find(@bkdetail.businesskpi_id)
    @kpi = Kpi.find(@bkdetail.kpi_id)
    
    respond_to do |format|
      if @bkdetail.save
        format.html { redirect_to action:"index", notice: 'Successfully added.' }
        format.json { render json: @bkdetail, status: :created, location: @bkdetail }
      else
        format.html { render action: "new" }
        format.json { render json: @bkdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @bkdetail = Bkdetail.find(params[:id])
      respond_to do |format|
        if @bkdetail.update_attributes(params[:bkdetail])
          format.html { redirect_to @bkdetail, notice: 'successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @bkdetail.errors, status: :unprocessable_entity }
        end
      end
  end

  def edit
    @bkdetail = Bkdetail.find(params[:id])
    @kpi = Kpi.find(@bkdetail.kpi_id) 
    @business = Business.find(@bkdetail.business_id)
    @bkpi = BusinessKpi.find(@bkdetail.businesskpi_id)  
  end

  def destroy
    @bkdetail = Bkdetail.find(params[:id])
    @bkdetail.destroy
      respond_to do |format|
        format.html { redirect_to @bkdetail }
        format.json { head :no_content }
      end
  end 

  def get_target_percentage
    actual_value = params[:actual_value]
    target_value = params[:target_value]
    percet =( (actual_value).to_f / (target_value).to_f * 100)-100
    render :text => percet
  end
  
  def dataEntry    
    freq = params[:KPIEntryPeriod] || "DAILY"
    @business = Business.find(params[:business_id]) 
    @mapped_kpi_ids = BusinessKpi.where(:business_id => @business.id,:kpi_id => Kpi.where(:KPIEntryPeriod => freq))
    @bkpi=BusinessKpi.new      
    respond_to do |format|
      format.html
      format.js
    end
end 

  def dataFeed
    @business = Business.find(params[:business_id])    
    @mapped_kpi_ids = BusinessKpi.where(:business_id => @business.id)    
  end  

end

app/helpers/bkdetails_helper.rb
module BkdetailsHelper
end

app/views/bkdetails/_form.html.erb
<div>
<h4>
  Add details
</h4>

<table class="table">
  <tr>        
    <th>Kpi Name</th>
    <th>Category</th>
    <th>Day</th>
    <th>Target</th>
    <th>Actual</th>
    <th>Target Percentage</th>
    <th>Notes</th>              
  </tr>

  <% @bks.each do |bk| %>
    <tr>    
      <td><%= bk.kpi.KPIName %></td>
      <td><%= bk.kpi.KPICategory %></td>
      <td><%= bk.logDate%></td> 
      <td><%= bk.targetValue %></td>
      <td><%= bk.actualValue %></td>
      <td><%= bk.targetPercentage %></td>     
      <td><%= bk.notes %></td>                           
    </tr>
  <% end %>
</table>
<br />
</div>

<div class="container">
  <table border="1">    

      <tr>
        <th>Kpi </br>Name</th>
        <th>Category</th>
        <th>Date</th>
        <th>Target</th>
        <th>Actual</th>
        <th>Target </br>Percentage</th>
        <th>Notes</th>        
      </tr>
  

    <tr>
      <%= form_for @bkdetail do |f| %>   
        <% if @bkdetail.errors.any? %>
          <div id="error_explanation">
          <h3><%= pluralize(@bkdetail.errors.count, "error") %> occured while processing:</h3>
          <ul>
            <% @bkdetail.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
          </div>
        <% end %>                
                
        <%= f.hidden_field :kpi_id,:value => @kpi.id%>
        <%= f.hidden_field :business_id,:value => @business.id%>  
        <%= f.hidden_field :businesskpi_id,:value => @bkpi.id%>  
        <td><%= @kpi.KPIName %></td>
        <td><%= @kpi.KPICategory %></td>
        <td>
          <% if @kpi.KPIEntryPeriod == 'DAILY'%>
            <%= f.text_field :logDate, :class => 'title simple custom date_picker_input', :maxlength => 5, :style => 'width:60px'%>
          <% elsif @kpi.KPIEntryPeriod == 'MONTHLY'%>
            <%= f.text_field :logDate, :class => 'title simple custom month_picker_input',:maxlength => 5, :style => 'width:60px'%>
          <% elsif @kpi.KPIEntryPeriod == 'QUARTERLY'%>
            <%= f.text_field :logDate, :class => 'title simple custom quarter_picker_input',:maxlength => 5, :style => 'width:60px'%> 
          <% elsif @kpi.KPIEntryPeriod == 'HALFYEARLY'%>
            <%= f.text_field :logDate, :class => 'title simple custom halfyear_picker_input',
            :maxlength => 5, :style => 'width:60px'%>
          <% else%>  
            <%= f.text_field :logDate, :class => 'title simple custom year_picker_input',
            :maxlength => 5, :style => 'width:60px'%>
          <%end%>
        </td>

        <td><%= f.text_field :targetValue ,:value => @kpi.KPITargetValue,:maxlength => 5, :style => 'width:60px'%></td>
        <td><%= f.text_field :actualValue,:maxlength => 5, :style => 'width:60px'%></td>
        <td><%= f.text_field :targetPercentage,:maxlength => 5,:style => 'width:60px'%></td>
        <td><%= f.text_field :notes,:maxlength => 5, :style => 'width:60px'%></td>                  
        <td>
          <div class="actions">
          <%= f.submit "save" ,:class=>["btn","btn-primary"] %>          
          </div>
        </td>    
      <%end%>
    </tr>

  </table>
</div>



<%= render 'plot' %>

app/views/bkdetails/_frequency.html.erb
<h4>Branch Kpi Details </h1>

<table class="table">
	
  <thead> 
        <th>Branch Name</th>
        <th>Kpi Category</th>
        <th>KPi Name</th>
        <th>KPI Frequency</th>        
  </thead>  

<% @mapped_kpi_ids.each do |mapped_kpi_id| %>
	<tr>	 
		<td><%= mapped_kpi_id.business.branchname%></td>	
	    <td><%= mapped_kpi_id.kpi.KPICategory%></td>
	    <td><%= mapped_kpi_id.kpi.KPIName%></td>	  	  
	    <td><%= mapped_kpi_id.kpi.KPIEntryPeriod%></td>	       
	    <td><%= link_to 'Add Data',new_bkdetail_path(:kpi_id => mapped_kpi_id.kpi_id,:business_id => @business.id,:businesskpi_id =>mapped_kpi_id.id),:class=> [:btn, :"btn-success"]%></td>   	    
	</tr>
<% end %> 






  

		

app/views/bkdetails/_plot.html.erb
<script type="text/javascript" src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1.1','packages':['corechart']}]}"></script>
    <script type="text/javascript">
      google.setOnLoadCallback(drawVisualization);

      function drawVisualization() {
        // Some raw data (not necessarily accurate)
        var data = google.visualization.arrayToDataTable([
          ['Date', 'Actual', 'Target'],
           <% @bks.each do |bic| %>
          ['<%= bic.logDate %>',<%= bic.actualValue rescue 0 %>,<%= bic.targetValue rescue 0%>],
          <% end %>
        ]);

        var options = {
          title : 'Performance Graph',
          vAxis: {title: "Actual"},
          hAxis: {title: "Date"},
          seriesType: "bars",
            series: {2:{type: "line"}}
        };

        var chart = new google.visualization.ComboChart(document.getElementById('rentals_trend_div'));
        chart.draw(data, options);
      }
    </script> 
<div id="rentals_trend_div" style="width: 900px; height: 500px;"></div>

app/views/bkdetails/_plot1.html.erb
<script type="text/javascript" src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1.1','packages':['corechart']}]}"></script>
    <script type="text/javascript">
      google.setOnLoadCallback(drawVisualization);

      function drawVisualization() {
        // Some raw data (not necessarily accurate)
        <% bks = Bkdetail.where("kpi_id = ? and business_id = ?",kpi_id,business_id) %>
        var data = google.visualization.arrayToDataTable([
          ['Date', 'Actual', 'Target'],
           <% bks.each do |bic| %>           
          ['<%= bic.logDate %>',<%= bic.actualValue rescue 0 %>,<%= bic.targetValue rescue 0%>],           
          <% end %>
        ]);

        var options = {
          title : 'Performance Graph',
          vAxis: {title: "Actual"},
          hAxis: {title: "Date"},
          seriesType: "bars",
            series: {2:{type: "line"}}
        };

        var chart = new google.visualization.ComboChart(document.getElementById('rentals_trend_div__<%= kpi_id%>'));
        chart.draw(data, options);
      }
    </script> 
<div id="rentals_trend_div__<%= kpi_id%>" style="width: 900px; height: 500px;"></div>

app/views/bkdetails/dataEntry.html.erb
<h4>Branch Kpi Details</h1>

<ul class="nav nav-tabs"  id="tabs">
  <li class="active">
  	<%= link_to 'Daily',"/bkdetails/dataEntry?business_id=#{@business.id}&KPIEntryPeriod=DAILY",:remote => true%>
  </li>
  <li>
  	<%= link_to 'Monthly',"/bkdetails/dataEntry?business_id=#{@business.id}&KPIEntryPeriod=MONTHLY",:remote => true%>
  </li>
</ul>  
<div class="tab-content">
  <div class="tab-pane active" id="kpi-freq-content">
   <%= render :partial => 'frequency' ,:locals => {:business_id => @business.id}%>
  </div>

app/views/bkdetails/dataEntry.js.erb
$("#kpi-freq-content").html("<%= escape_javascript(render :partial => 'frequency') %>");

app/views/bkdetails/dataFeed.html.erb
<h4>Branch Kpi Details</h1>

<table class="table">
  <thead> 
        <th>Feed For </th>
        <th>Branch Name</th>
        <th>Kpi Category</th>
        <th>KPi Name</th>
        <th>KPI Frequency</th>        
  </thead>  

<% @mapped_kpi_ids.each do |mapped_kpi_id| %>
  <tr>   
    
      <td><%= Time.now.strftime("%m/%d/%Y") %></td>            
      <td><%= mapped_kpi_id.business.branchname%></td>
      <td><%= mapped_kpi_id.kpi.KPICategory%></td>
      <td><%= mapped_kpi_id.kpi.KPIName%></td>        
      <td><%= mapped_kpi_id.kpi.KPIEntryPeriod%></td>       
      <td><%= render :partial => 'plot1',:locals => {:kpi_id => mapped_kpi_id.kpi_id,:business_id => @business.id}%></td>      
  </tr>
<% end %>
	</tr>
</table>

app/views/bkdetails/edit.html.erb
<h4>Edit Details</h4>

 <table border="1"> 
 <%= form_for @bkdetail do |f| %>   
        <% if @bkdetail.errors.any? %>
          <div id="error_explanation">
          <h3><%= pluralize(@bkdetail.errors.count, "error") %> occured while processing:</h3>
          <ul>
            <% @bkdetail.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
          </div>
        <% end %>
            
                
        <%= f.hidden_field :kpi_id,:value => @kpi.id%>
        <%= f.hidden_field :business_id,:value => @business.id%>  
        <%= f.hidden_field :businesskpi_id,:value => @bkpi.id%>  
        <td><%= @kpi.KPIName %></td>
        <td><%= @kpi.KPICategory %></td>
        <td>
          <% if @kpi.KPIEntryPeriod == 'DAILY'%>
            <%= f.text_field :logDate, :class => 'title simple custom date_picker_input', :maxlength => 5, :style => 'width:60px'%>
          <% elsif @kpi.KPIEntryPeriod == 'MONTHLY'%>
            <%= f.text_field :logDate, :class => 'title simple custom month_picker_input',:maxlength => 5, :style => 'width:60px'%>
          <% elsif @kpi.KPIEntryPeriod == 'QUARTERLY'%>
            <%= f.text_field :logDate, :class => 'title simple custom quarter_picker_input',:maxlength => 5, :style => 'width:60px'%> 
          <% elsif @kpi.KPIEntryPeriod == 'HALFYEARLY'%>
            <%= f.text_field :logDate, :class => 'title simple custom halfyear_picker_input',
            :maxlength => 5, :style => 'width:60px'%>
          <% else%>  
            <%= f.text_field :logDate, :class => 'title simple custom year_picker_input',
            :maxlength => 5, :style => 'width:60px'%>
          <%end%>
        </td>

        <td><%= f.text_field :targetValue ,:value => @kpi.KPITargetValue,:maxlength => 5, :style => 'width:60px'%></td>
        <td><%= f.text_field :actualValue,:maxlength => 5, :style => 'width:60px'%></td>
        <td><%= f.text_field :targetPercentage,:maxlength => 5,:style => 'width:60px'%></td>
        <td><%= f.text_field :notes,:maxlength => 5, :style => 'width:60px'%></td>                  
        <td>
          <div class="actions">
          <%= f.submit "save" ,:class=>["btn","btn-primary"] %>          
          </div>
        </td>    
      <%end%>
    </tr>

  </table>
</div>



     
<%= link_to "Back", bkdetails_path,:class=>["btn","btn-default"] ,:id=>"backbutton"%>
<%= link_to 'Show', @bkdetail,:class=>["btn","btn-default"] ,:id=>"backbutton" %> 
    

app/views/bkdetails/index.html.erb
<div>
  <h4>
     Add details
  </h4>

<table class="table">
  <thead>    
    <th>Target</th> 
    <th>Actual</th>         
    <th>Day</th>
    <th>Notes</th>  
  </thead>

<% @bks.each do |bkdetail| %>
  <tr>
    <td><%= bkdetail.targetValue %></td>               
    <td><%= bkdetail.actualValue %></td>
    <td><%= bkdetail.logDate%></td> 
    <td><%= bkdetail.notes %></td>   
    <td><%= link_to 'Show', bkdetail %>  <%= link_to 'Edit', edit_bkdetail_path(bkdetail) %>
        <%= link_to 'Destroy',bkdetail, method: :delete, data: {confirm: 'Are you sure?'} %> 
    </td>    
  </tr>
<% end %>

</table>
<br />
</div>

app/views/bkdetails/new.html.erb
<%= render 'form' %>

app/views/bkdetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b> Target:</b>
  <%= @bkdetail.targetValue %>
</p>

<p>
  <b> Actual:</b>
  <%= @bkdetail.actualValue %>
</p>

<p>
  <b> Notes</b>
  <%= @bkdetail.notes %>
</p>


<%= link_to 'Edit', edit_bkdetail_path %> |
<%= link_to 'Back', bkdetails_path %>