config/routes.rb
SimpleKpi::Application.routes.draw do

    resources :kpis
    resources :businesskpis  

   
    resources :bkdetails do 
      collection do 
        get 'dataEntry'
        get 'dataFeed'
      end
    end 

    get 'businesses/home'
    resources :franchisemasters   

    resources :businesses do
      collection do
        post 'savelinkkpi'
        get 'businesslinkkpi'        
      end
    end

  match '/get_target_percentage' => 'bkdetails#get_target_percentage'

  namespace :api do 
    namespace :v1 do
     post 'kpis/create' => 'kpis#create'
     post 'bkdetails/create' => 'bkdetails#create'
    end

  end

                         

  root :to => 'businesses#home'

end

app/models/franchisemaster.rb
class Franchisemaster < ActiveRecord::Base
  attr_accessible :address, :business_id, :effectivefrom, :emailid, :franchiseename, :franchisename, :franchisetype, :openingdate

  validates :franchisetype,:franchisename,:franchiseename,:emailid,:address,:openingdate,:effectivefrom,:presence => true
  validates :franchisetype,:franchisename,:franchiseename, :length => { :maximum =>10 }
  validates :franchisename, :uniqueness => true
end

app/controllers/franchisemasters_controller.rb
class FranchisemastersController < ApplicationController

  def index
    @franchisemasters = Franchisemaster.all
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render json: @franchisemasters }
	  end
  end

  def new
	  @franchisemaster = Franchisemaster.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @franchisemaster }
      end
  end

  def show
    @franchisemaster = Franchisemaster.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @franchisemaster }
    end
  end

  def create
    @franchisemaster = Franchisemaster.new(params[:franchisemaster])
      respond_to do |format|
        if @franchisemaster.save
          format.html { redirect_to @franchisemaster, notice: 'Franchise successfully added.' }
          format.json { render json: @franchisemaster, status: :created, location: @franchisemaster }
        else
          format.html { render action: "new" }
          format.json { render json: @franchisemaster.errors, status: :unprocessable_entity }
        end
      end
  end

  def update
	  @franchisemaster = Franchisemaster.find(params[:id])
      respond_to do |format|
        if @franchisemaster.update_attributes(params[:franchisemaster])
          format.html { redirect_to @franchisemaster, notice: 'Franchise Details successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @franchisemaster.errors, status: :unprocessable_entity }
        end
      end
    end

  def edit
	  @franchisemaster = Franchisemaster.find(params[:id])
  end


  def destroy
    @franchisemaster = Franchisemaster.find(params[:id])
    @franchisemaster.destroy

      respond_to do |format|
        format.html { redirect_to @franchisemaster }
        format.json { head :no_content }
      end
  end

end

app/helpers/franchisemasters_helper.rb
module FranchisemastersHelper
end

app/views/franchisemasters/_form.html.erb
<%= form_for @franchisemaster do |f| %>
  <% if @franchisemaster.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@franchisemaster.errors.count, "error") %> occured while processing:</h3>
      <ul>
      <% @franchisemaster.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>    
  <br />
    
  <h4>Franchise Details</h4>
    
    <div>
      <%= f.label 'Franchise Type*' %>
      <%= f.text_field :franchisetype, :class => 'title simple', :maxlength => 50, :style => 'width:633px'%>
    </div>
    
    <div >
      <%= f.label 'Franchise Name*' %>
        <%= f.text_field :franchisename %>
    </div>
   
    <div>
      <%= f.label 'Franchisee Name*'%>
      <%= f.text_field :franchiseename, :class => 'title simple', :maxlength => 50, :style => 'width:633px'%>
    </div>
    
    <div>
      <%= f.label 'Email*'%>  
      <%= f.text_field :emailid,:class => 'title simple', :maxlength => 50, :style => 'width:633px'%>
    </div>   
    

    <div>
      <%= f.label 'Address*'%>  
      <%= f.text_field :address,:class => 'title simple', :maxlength => 50, :style => 'width:633px'%>
    </div>  

    
    <div>
      <%= f.label 'Opening Date*'%>
      <%= f.text_field :openingdate, :class => 'title simple', :maxlength => 500, :style => 'width:633px'%>
    </div>
    

    <div>
      <%= f.label 'Effective From*'%>
      <%= f.text_field :effectivefrom, :class => 'title simple', :maxlength => 50, :style => 'width:633px'%>
    </div>


    <div>
      <%= f.label 'Business Id'%>  
      <%= f.text_field :business_id,:class => 'title simple', :maxlength => 50, :style => 'width:633px'%>
    </div> 
              
    <div class="actions">
            <%=f.submit "Submit" ,:class=>["btn","btn-primary"] %>
    </div>

<% end %>
    

app/views/franchisemasters/edit.html.erb
<h4>Edit Franchisee Details</h4>
<%= render 'form' %>

    
<%= link_to "Back", franchisemaster_path,:class=>["btn","btn-default"] ,:id=>"backbutton"%>
<%= link_to 'Show', @franchisemaster,:class=>["btn","btn-default"] ,:id=>"backbutton" %> 
    

app/views/franchisemasters/index.html.erb
<div>
  <h4>
    <%= link_to  new_franchisemaster_path, :class => [:btn, :"btn-success"] do |l|%>
      <i class="icon-plus-sign icon-white"></i>
      Add New Franchisee
    <% end %>
  </h4>
<table class="table table-striped table-bordered">
  <thead>
    <th>Franchise Type</th>          
    <th>Franchise Name</th>
    <th>Owner Email</th>            
  </thead>

<% @franchisemasters.each do |franchisemaster| %>
  <tr>
    <td><%= franchisemaster.franchisetype %></td>               
    <td><%= franchisemaster.franchiseename %></td>
    <td><%= franchisemaster.emailid%></td>               
    <td><%= link_to 'Show',franchisemaster %>  <%= link_to 'Edit', edit_franchisemaster_path(franchisemaster)%>
        <%= link_to 'Destroy',franchisemaster, method: :delete, data: {confirm: 'Are you sure?'} %> 
        <%= link_to 'AddBusiness',new_business_path,:class=>["btn","btn-default"] %>  
    </td>
  </tr>
<% end %>
</table>
<br />
</div>

app/views/franchisemasters/new.html.erb
<%= render 'form' %> 
<%= link_to 'Back',franchisemasters_path %>

app/views/franchisemasters/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Franchise Type:</b>
  <%= @franchisemaster.franchisetype %>
</p>

<p>
  <b>Franchise Name:</b>
  <%= @franchisemaster.franchisename %>
</p>

<p>
  <b>Franchisee Name:</b>
  <%= @franchisemaster.franchisename %>
</p>

<p>
  <b>Owner Email:</b>
  <%= @franchisemaster.emailid%>
</p>

<p>
  <b>Owner Address:</b>
  <%= @franchisemaster.address%>
</p>


<p>
  <b>Opening Date: </b>
  <%= @franchisemaster.openingdate %>
</p>

<p>
  <b>Effective From</b>
  <%= @franchisemaster.effectivefrom %>
</p>


<%= link_to 'Edit', edit_franchisemaster_path %> |
<%= link_to 'Back', franchisemasters_path %>