config/routes.rb
SimpleKpi::Application.routes.draw do

    resources :kpis
    resources :businesskpis  

   
    resources :bkdetails do 
      collection do 
        get 'dataEntry'
        get 'dataFeed'
      end
    end 

    get 'businesses/home'
    resources :franchisemasters   

    resources :businesses do
      collection do
        post 'savelinkkpi'
        get 'businesslinkkpi'        
      end
    end

  match '/get_target_percentage' => 'bkdetails#get_target_percentage'

  namespace :api do 
    namespace :v1 do
     post 'kpis/create' => 'kpis#create'
     post 'bkdetails/create' => 'bkdetails#create'
    end

  end

                         

  root :to => 'businesses#home'

end

app/models/kpi.rb
class Kpi < ActiveRecord::Base
  attr_accessible :KPICategory, :KPIDirection, :KPIEntryPeriod, :KPIName, :KPITargetValue, :KPIUnitName, :active
  
  has_many :bkdetails
  has_many :businesskpi

  validates :KPICategory, :KPIDirection, :KPIEntryPeriod, :KPIName, :KPITargetValue, :KPIUnitName,:presence => true
  validates :KPIName, :length => { :maximum =>10 }
  validates :KPIName,:uniqueness => true
 
end

app/controllers/api/v1/kpis_controller.rb
class Api::V1::KpisController < ApplicationController

  respond_to :xml, :json
    
  def create
    
    @kpi= Kpi.new
    @kpi.KPIName = params[:kpi_data][:KPIName]
    @kpi.KPIEntryPeriod = params[:kpi_data][:KPIEntryPeriod]
    @kpi.KPICategory = params[:kpi_data][:KPICategory]
    @businesskpi = BusinessKpi.new
    if Kpi.exists?(KPIName: @kpi.KPIName)
      @businesskpi.business_id = params[:kpi_data][:BusinessID] 
      @businesskpi.kpi_id = @kpi.id

    else      
    @kpi.KPIDirection ="None"  
    @kpi.KPIUnitName="1,234"
    @kpi.KPITargetValue=900
    if @kpi.save
      @businesskpi.business_id = params[:kpi_data][:BusinessID]   
      @businesskpi.kpi_id = @kpi.id
          else
       render :json => {:errors => @kpi.errors.full_messages }
       end
    end 


    if @businesskpi.save
       render :json => @businesskpi.to_json
     else
       render :json => {:errors => @businesskpi.errors.full_messages }
       end  
  end 

end 

app/controllers/kpis_controller.rb
class KpisController < ApplicationController
  
  def index
    @kpis = Kpi.all
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render json: @kpis }
	   end
  end  
  
  def new
    @kpi = Kpi.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @kpi  }
      end
  end
 
  def show
    @kpi = Kpi.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: kpis}
      end
  end

  def create
    @kpi = Kpi.new(params[:kpi])
      respond_to do |format|
        if @kpi.save
          format.html { redirect_to action:"index", notice: 'Successfully added.' }
          format.json { render json: @kpi, status: :created, location: @kpi }
        else
          format.html { render action: "new" }
          format.json { render json: @kpi.errors, status: :unprocessable_entity }
        end
      end
  end

  def update
	  @kpi = Kpi.find(params[:id])
      respond_to do |format|
        if @kpi.update_attributes(params[:kpi])
          format.html { redirect_to @kpi, notice: 'successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @kpi.errors, status: :unprocessable_entity }
        end
      end
  end

  def edit
	  @kpi = Kpi.find(params[:id])
  end


  def destroy
    @kpi = Kpi.find(params[:id])
    @kpi.destroy
      respond_to do |format|
        format.html { redirect_to @kpi }
        format.json { head :no_content }
      end
  end  
end   

app/helpers/kpis_helper.rb
module KpisHelper
end

app/views/kpis/_form.html.erb
  <%= form_for @kpi do |f| %>
    <% if @kpi.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(@kpi.errors.count, "error") %> occured while processing:</h3>
        <ul>
        <% @kpi.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>    
    <h4> Add KPI </h4>
    <div>
      <%= f.label 'Give your KPI a name' %>
      <%= f.text_field :KPIName, :class => 'title simple custom', :maxlength => 50, :style => 'width:633px'%>
    </div>
    
    <div>
      <%= f.label 'When will this KPI be entered' %>
        <%= f.select :KPIEntryPeriod,%w{DAILY MONTHLY QUARTERLY HALFYEARLY YEARLY},:include_blank => true %> 
    </div>
   
    <div>
      <%= f.label 'What is your KPI format?'%>
      <%= f.select :KPIUnitName,%w{1,234 1234.5 12min 12hrs}, :maxlength => 50, :style => 'width:633px'%>
    </div>
    
    <div>
      <%= f.label 'Which direction is best?'%>  
      <%= f.select :KPIDirection,["Up","Down","None"],:include_blank => true %>
    </div>
    
    <div>
      <%= f.label 'Does the KPI have a target'%>
      <%= f.text_field :KPITargetValue, :class => 'title simple', :maxlength => 500, :style => 'width:633px'%>
    </div>
    
    <div>
      <%= f.label 'Which Category'%>
      <%= f.select :KPICategory,["Collection Today","Renewals Today","Signup Today","AttritionToday","Circulation Today" ],:include_blank => true%>
    </div>     
    
    <div class="actions">
      <%=f.submit "Save" ,:class=>["btn","btn-primary"] %>
      <%= link_to "Cancel", :back, :class=>["btn","btn-primary"] %>
    </div>      
    </br>

<% end %>

app/views/kpis/edit.html.erb
<h4>Editing Branch Details</h4>
<%= render 'form' %>      
<%= link_to "Back", kpis_path,:class=>["btn","btn-default"] ,:id=>"backbutton"%>
<%= link_to 'Show', @kpi,:class=>["btn","btn-default"] ,:id=>"backbutton" %> 
    

app/views/kpis/index.html.erb
<div>
  <h4>
    <%= link_to  new_kpi_path, :class => [:btn, :"btn-success"] do |l|%>
      <i class="icon-plus-sign icon-white"></i>
      Add KPI
    <% end %>
  </h4>

<table class="table">
  <thead>    
    <th>KPI Name</th> 
    <th>Format</th>         
    <th>Frequency</th>
    <th>Direction</th>  
    <th>Target</th>
    <th>Entries</th>
    <th>KPI Status</th>
  </thead>

<% @kpis.each do |kpi| %>  
  <tr>    
    <td><%= kpi.KPIName %></td>   
    <td><%= kpi.KPIUnitName %></td>
    <td><%= kpi.KPIEntryPeriod%></td> 
    <td><%= kpi.KPIDirection %></td>       
    <td><%= kpi.KPITargetValue %></td>               
    <td><%=link_to 'Add Data',new_bkdetail_path(:kpi_id => kpi.id),:class => [:btn, :"btn-success"]%></td>
    <td><%=link_to '[disable]' %></td>
    <td><%= link_to 'Show', kpi %>  <%= link_to 'Edit', edit_kpi_path(kpi) %>
        <%= link_to 'Destroy',kpi, method: :delete, data: {confirm: 'Are you sure?'} %>  
    </td>   
  </tr>
<% end %>
</table>
<br />
</div>

app/views/kpis/new.html.erb
<%= render 'form' %>  

app/views/kpis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Kpi Name:</b>
  <%= @kpi.KPIName %>
</p>

<p>
  <b>Kpi Format</b>
  <%= @kpi.KPIUnitName %>
</p>

<p>
  <b>Kpi Frequency</b>
  <%= @kpi.KPIEntryPeriod %>
</p>


<%= link_to 'Edit', edit_kpi_path %> |
<%= link_to 'Back', kpis_path %>